[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "flowers-analytics"
version = "0.1.0"
dependencies = ["pyspark"]

[tool.setuptools.packages.find]
where = ["src"]
